services:
  mongodb:
    container_name: mongo
    build: .
    image: mongo:7.0.5-jammy
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017","--keyFile","/data/replica.key" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: ".env"
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    restart: always